version: '3.8'

services:

  jupiterinv.api:
    image: jupiterinv.api
    build:
      context: . 
      dockerfile: JupiterInv.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_Kestrel__Certificates__Default__Password=2099
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ~/.aspnet/https:/https:ro

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: jupiterinvdb
      POSTGRES_USER: philo
      POSTGRES_PASSWORD: 2099
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
